name: Update infrastructure-docker submodule

on:
  push:
    branches:
      - main

jobs:
  job-1:
    name: Update keycloak submodule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "ai4c-ai/keycloak"
          submodules: true
      - name: Update submodule
        run: |
          cd keycloak-user-creation-events
          git checkout ${{ github.sha }}
      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update keycloak-user-creation-events
          branch: update/keycloak-user-creation-events
          token: ${{ secrets.KEYCLOAK_PUSH_SECRET }}
      - name: Set to auto merge
        run: gh pr merge update/keycloak-user-creation-events --auto --merge -R ai4c-ai/keycloak
        env:
          GH_TOKEN: ${{ secrets.KEYCLOAK_PUSH_SECRET }}
